[package]
name = "worlds-reincarnate"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
thiserror = "2.0.9"
rfd = "0.15.2"

mc-classic-js = "0.1.4"
mc-classic = { git = "https://github.com/Sl1mj1m14/rust-mc-classic.git" }