import { Theme } from "themes/theme.slint";

export component ThemeText inherits Text { color: Theme.text; }

export component HeaderText inherits ThemeText {
    font-size: 12pt;
    vertical-alignment: center;
    horizontal-alignment: center;
    overflow: elide;
}

export component HoverButton inherits Rectangle {
    callback clicked <=> ta.clicked;
    in property <string> text;
    in-out property <bool> has_hover: ta.has-hover;
    in property <bool> enabled;

    Text { text: text; }

    ta := TouchArea {
        enabled: enabled;
    }

}
