import { Button, ComboBox, ListView, VerticalBox } from "std-widgets.slint";
import { Theme } from "themes/theme.slint";
import { HeaderText, ThemeText } from "components.slint";

struct Version {
    display: string,
    value: int
}

export global Constants {
    in-out property <string> js-value;
}

export global Versions {
    in-out property <[string]> editions;

    in-out property <string> input-state;
    in-out property <string> input-edition;
    in-out property <string> input-version;
    in-out property <[Version]> input-version-list;

    in-out property <string> output-state;
    in-out property <string> output-edition;
    in-out property <string> output-version;
    in-out property <[Version]> output-version-list;

    in-out property <[string]> js-format-list;
    in-out property <[string]> js-url-list;

    callback set-version(mode: int, edition: int, samvid: int);
    callback set-edition(mode: int, edition: int);
    callback update-args(mode: int, state: string, args: [int]);
    callback browse();
    callback convert();
}

component Settings inherits Rectangle {
    height: 25px;
    background: Theme.background-secondary;
}

component Header inherits Rectangle {
    height: 100px;
    background: Theme.background-primary;

    HorizontalLayout {
        spacing: 15px;
        alignment: stretch;

        HeaderText { text: Versions.input-edition + "    " + Versions.input-version; }

        Button {
            width: 150px;
            text: "[PLACEHOLDER]";
            clicked => { Versions.convert(); }
        }

        HeaderText { text: Versions.output-edition + "    " + Versions.output-version; }
    }
}

component Input inherits VerticalLayout {
    padding: 15px;

    input-header := HorizontalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            HeaderText {
                text: "INPUT";
            }
            Button {
                text: "x";
                width: 25px;
                clicked => { Versions.browse(); }
            }
        }
    }

    ThemeText { text: "Choose Edition:"; }

    input-edition-box := ComboBox {
        model: Versions.editions;
        selected(val) => {
            Versions.set-edition(0, input-edition-box.current-index);
            Versions.input-edition = val;
            Versions.input-version = "";
        }
    }

    ThemeText { text: "Select Version:"; }

    input-version-list := ListView {
        min-height: 100px;
        horizontal-scrollbar-policy: always-off;

        for version in Versions.input-version-list:
            Button {
                height: 25px;
                text: version.display;
                clicked() => {
                    Versions.set-version(0, input-edition-box.current-index, version.value);
                    Versions.input-edition = input-edition-box.current-value;
                    Versions.input-version = version.display;
                }
            }
    }

    if (Versions.input-state == Constants.js-value) : VerticalBox {
        ThemeText { text: "Choose Format:"; }
        js-format := ComboBox {
            model: Versions.js-format-list;
            selected(_) => {
                Versions.update-args(0, Versions.input-state, [js-format.current-index, js-url.current-index])
            }
        }
        ThemeText { text: "Choose Url:"; }
        js-url := ComboBox {
            model: Versions.js-url-list;
            selected(_) => {
                Versions.update-args(0, Versions.input-state, [js-format.current-index, js-url.current-index])
            }
        }
    }
}

component Output inherits VerticalLayout {
    padding: 15px;

    HeaderText { 
        height: 30px; 
        text: "OUTPUT"; 
    }

    ThemeText { text: "Choose Edition:"; }

    output-edition-box := ComboBox {
        model: Versions.editions;
        selected(val) => {
            Versions.set-edition(0, output-edition-box.current-index);
            Versions.output-edition = val;
            Versions.output-version = "";
        }
    }

    ThemeText { text: "Select Version:"; }

    output-version-list := ListView {
        min-height: 100px;
        horizontal-scrollbar-policy: always-off;

        for version in Versions.output-version-list:
            Button {
                height: 25px;
                text: version.display;
                clicked() => {
                    Versions.set-version(0, output-edition-box.current-index, version.value);
                    Versions.output-edition = output-edition-box.current-value;
                    Versions.output-version = version.display;
                }
            }
    }

    if (Versions.output-state == Constants.js-value) : VerticalBox {
        ThemeText { text: "Choose Format:"; }
        js-format := ComboBox {
            model: Versions.js-format-list;
            selected(_) => {
                Versions.update-args(0, Versions.output-state, [js-format.current-index, js-url.current-index])
            }
        }
        ThemeText { text: "Choose Url:"; }
        js-url := ComboBox {
            model: Versions.js-url-list;
            selected(_) => {
                Versions.update-args(0, Versions.output-state, [js-format.current-index, js-url.current-index])
            }
        }
    }
}

export component ConvertScreen {

    VerticalLayout {
        Settings {}

        Header {}

        body := Rectangle {
            background: Theme.background-primary;

            HorizontalLayout {
                Input {}
                Output {}
            }
        }
    }
}