import { ConvertScreen, Versions, Constants } from "convert.slint";
import { LoadScreen } from "load.slint";
import { UIState, State } from "states.slint";

export { Versions, Constants, UIState, State }

export component MainWindow inherits Window {

    title: "Worlds Reincarnate";

    preferred-height: 500px;
    preferred-width: 500px;

    min-height: 300px;
    min-width: 200px;

    if (UIState.state == State.load) : LoadScreen { height: root.height; width: root.width; }
    if (UIState.state == State.convert) : ConvertScreen { height: root.height; width: root.width; }
}