import { ConvertScreen, Versions, Constants } from "convert.slint";
import { LoadScreen } from "load.slint";

export { Versions, Constants }

export enum State { load, convert }

export component MainWindow inherits Window {

    in-out property <State> state : State.load;

    title: "Worlds Reincarnate";

    preferred-height: 600px;
    preferred-width: 800px;

    min-height: 300px;
    min-width: 500px;

    loading-screen := LoadScreen { height: root.height; width: root.width; visible: true; }
    converting-screen := ConvertScreen { height: root.height; width: root.width; visible: false; }

    states [
        loading when (state == State.load) : {
            loading-screen.visible: true;
            converting-screen.visible: false;
        }
        converting when (state == State.convert) : {
            loading-screen.visible: false;
            converting-screen.visible: true;
        }
    ]
}