import { ConvertScreen, Versions, Constants } from "convert.slint";
import { LoadScreen } from "load.slint";

export { Versions, Constants }

export enum State { load, convert }

export component MainWindow inherits Window {
    in-out property <State> state : State.load;

    title: "Worlds Reincarnate";

    preferred-height: 500px;
    preferred-width: 500px;

    min-height: 300px;
    min-width: 200px;

    if (state == State.load) : LoadScreen { height: root.height; width: root.width; }
    if (state == State.convert) : ConvertScreen { height: root.height; width: root.width; }
}